### ISSUE TITLE
Query with AND operator

### ISSUE THREAD

**Issue by un1t** [mozilla/elasticutils#291]
This example uses default OR operator. 

```
q = S().query(title__match='taco trucks')
```

It is possible to use here AND operator?

**Comment by sabine** [comment]
@un1t Are you deeply invested in using ElasticUtils? If the answer is no, use https://github.com/elasticsearch/elasticsearch-dsl-py instead (as suggested in README). There, you can easily use all the features of Elasticsearch in a straight-forward way.

Just saying, because this is no longer maintained and my experience has been that transitioning the queries to elasticsearch-dsl-py was not hard. The mapping classes and indexing tasks for django are convenient, though - I still use these.

**Comment by un1t** [comment]
I did not know that project is not maintaned anymore. So, OK, I'll switch to elasticsearch-dsl-py.

**Comment by willkg** [comment]
I wrote up a blog post about some things we did when converting:

http://bluesock.org/~willkg/blog/mozilla/ditching_elasticutils.html

**Comment by un1t** [comment]
Thank you!
